name: Pre-Release

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install make
        run: sudo apt update && sudo apt install build-essential
      - name: Build All targets
        run: make VERBOSE="-v" all
      - name: Release Binary
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "pre-release"
          title: "Pre-release"
          files: |
            bin/*
