name: Generate CONFIG.md

on:
  push:
    branches: [ "master" ]
    paths:
      - config/**
      - extras/generate.go
  workflow_dispatch:

jobs:
  default_conf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Generate CONFIG.md
      run: go run extras/generate.go

    - name: Commit CONFIG.md
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate CONFIG.md
